### TESTS DES QUESTIONNAIRES

### 1. Récupérer tous les questionnaires
GET http://localhost:5000/quiz/api/v1.0/questionnaires
Accept: application/json

### 2. Créer un nouveau questionnaire
POST http://localhost:5000/quiz/api/v1.0/questionnaires
Content-Type: application/json

{
    "name": "Astronomie"
}

### 3. Récupérer un questionnaire spécifique (ici le 1)
GET http://localhost:5000/quiz/api/v1.0/questionnaires/1
Accept: application/json

### 4. Modifier le nom d'un questionnaire 
PUT http://localhost:5000/quiz/api/v1.0/questionnaires/1
Content-Type: application/json

{
    "name": "Géographie & Monde"
}

### TESTS DES QUESTIONS


### 5. Récupérer toutes les questions du questionnaire 1
GET http://localhost:5000/quiz/api/v1.0/questionnaires/1/questions
Accept: application/json

### 6. Ajouter une Question Ouverte
POST http://localhost:5000/quiz/api/v1.0/questionnaires/1/questions
Content-Type: application/json

{
    "title": "Quelle est la capitale de l'Islande ?",
    "reponse": "Reykjavik"
}

### 7. Ajouter une Question QCM 
POST http://localhost:5000/quiz/api/v1.0/questionnaires/1/questions
Content-Type: application/json

{
    "title": "Quelle est la plus grande planète ?",
    "p1": "Mars",
    "p2": "Jupiter",
    "bonne_reponse": 2
}

### 8. Ajouter une Question standard
POST http://localhost:5000/quiz/api/v1.0/questionnaires/1/questions
Content-Type: application/json

{
    "title": "Question"
}

### 9. Récupérer une question précise (Question 1 du Questionnaire 1)
GET http://localhost:5000/quiz/api/v1.0/questionnaires/1/questions/1
Accept: application/json

### TESTS DE MODIFICATION ET SUPPRESSION

### 10. Modifier une Question Ouverte
PUT http://localhost:5000/quiz/api/v1.0/questionnaires/1/questions/1
Content-Type: application/json

{
    "title": "Capitale de l'Islande (Modifiée)",
    "reponse": "Reykjavík"
}

### 11. Modifier une Question QCM
PUT http://localhost:5000/quiz/api/v1.0/questionnaires/1/questions/2
Content-Type: application/json

{
    "title": "Quelle est la planète la plus proche du soleil ?",
    "p1": "Mercure",
    "p2": "Vénus",
    "bonne_reponse": 1
}

### 12. Supprimer une question spécifique
DELETE http://localhost:5000/quiz/api/v1.0/questionnaires/1/questions/3

### 13. Supprimer un questionnaire complet
DELETE http://localhost:5000/quiz/api/v1.0/questionnaires/3